In [1]:
import numpy as np
import pandas as pd

In [2]:
# ESI =Xkmin(XackXac, XbckXbc) x 100
# C_ij=Σ[(RCAxik * RCAmjk)]*[W_k/W]。

In [3]:
data = pd.read_excel(r"C:\Users\lll23\Documents\WXWork\1688857525503677\Cache\File\2024-04\202403..出口.xlsx",sheet_name="世界贸易数据库-年度（分国家HS2012）")

In [44]:
data

统计国     年 贸易国                                        商品   进口金额（美元）  \
0       中国  2012  缅甸  300210 - 抗血清、其他血份及免疫制品,不论是否修饰或通过生物工艺加工制得        NaN   
1       中国  2012  缅甸                             380110 - 人造石墨        NaN   
2       中国  2012  缅甸              382200 - 诊断或实验用试剂及配制试剂;检定参照物        NaN   
3       中国  2012  缅甸                   390760 - 初级形状的聚对苯二甲酸乙二酯        NaN   
4       中国  2012  缅甸             845610 - 用激光、其他光或光子束处理材料的加工机床        NaN   
...    ...   ...  ..                                       ...        ...   
1878  中国大陆  2022  泰国                          852349 - 已录制光学媒体  1593253.0   
1879  中国大陆  2022  文莱               847130 - 重量≤10kg的便携自动数据处理设备        NaN   
1880  中国大陆  2022  文莱                 847780 - 其他橡胶或塑料及其产品的加工机器        NaN   
1881  中国大陆  2022  文莱                           850231 - 风力发电机组        NaN   
1882  中国大陆  2022  文莱                           850760 - 锂离子蓄电池        NaN   

       出口金额（美元）  
0      132835.0  
1         883.0  
2      241176.0  
3     2607291.0  
4      264860.0  
...         ...  
1878   736470.0  
1879   229579.0  
1880    62959.0  
1881     3466.0  
1882  1202126.0  

[1883 rows x 6 columns]

In [45]:
# data = new_data

In [5]:
data.index = range(len(data))

In [6]:
mm = data.groupby(["年","贸易国"])["出口金额（美元）"].sum()

In [7]:
data["年"] = data["年"].astype(str)

In [8]:
data_sum = data.drop_duplicates().groupby(["年","贸易国"]).size().reset_index(name='sum')

In [9]:
data_sum["sum"] = np.array(mm)

In [10]:
vue = data["出口金额（美元）"]

In [11]:
bq = data[["年","贸易国"]] == data_sum.iloc[0][:-1]

In [29]:
data_sum

年    贸易国           sum
0    2012     印度  3.504356e+09
1    2012  印度尼西亚  1.482425e+09
2    2012     文莱  1.124241e+07
3    2012    新加坡  2.094756e+09
4    2012    新西兰  2.798262e+08
..    ...    ...           ...
165  2022     老挝  5.808275e+06
166  2022    菲律宾  7.240476e+08
167  2022     越南  3.778508e+09
168  2022     韩国  8.025483e+09
169  2022   马来西亚  1.382976e+09

[170 rows x 3 columns]

In [12]:
date_ = data.copy()
for i in range(len(data_sum)):
    bq = data[["年","贸易国"]] == data_sum.iloc[i][:-1]
    date_.iloc[date_[bq.iloc[:,0]][bq.iloc[:,1]].index,5] = data[bq.iloc[:,0]][bq.iloc[:,1]]["出口金额（美元）"]/data_sum.iloc[i][-1]

C:\Users\lll23\AppData\Local\Temp\ipykernel_27872\2836221336.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  date_.iloc[date_[bq.iloc[:,0]][bq.iloc[:,1]].index,5] = data[bq.iloc[:,0]][bq.iloc[:,1]]["出口金额（美元）"]/data_sum.iloc[i][-1]
C:\Users\lll23\AppData\Local\Temp\ipykernel_27872\2836221336.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  date_.iloc[date_[bq.iloc[:,0]][bq.iloc[:,1]].index,5] = data[bq.iloc[:,0]][bq.iloc[:,1]]["出口金额（美元）"]/data_sum.iloc[i][-1]
C:\Users\lll23\AppData\Local\Temp\ipykernel_27872\2836221336.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  date_.iloc[date_[bq.iloc[:,0]][bq.iloc[:,1]].index,5] = data[bq.iloc[:,0]][bq.iloc[:,1]]["出口金额（美元）"]/data_sum.iloc[i][-1]
C:\Users\lll23\AppData\Local\Temp\ipykernel_27872\2836221336.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  date_.iloc[date_[bq.iloc[:,0]][bq.iloc[:,1]].index,5] 

In [13]:
date_ck = date_[["年","贸易国","商品","出口金额（美元）"]]

In [14]:
dq_and_dz = ['847130 - 重量≤10kg的便携自动数据处理设备','850760 - 锂离子蓄电池','851712 - 用于蜂窝网络或其他无线网络的电话机','852349 - 已录制光学媒体','854140 - 光敏半导体器件;发光二极管','854140 - 光敏半导体器件；发光二极管']
jx_and_sb = ['845610 - 用激光、其他光或光子束处理材料的加工机床','847780 - 其他橡胶或塑料及其产品的加工机器','850231 - 风力发电机组']
t_h_j = ['720299 - 未列名铁合金']
qx = ['382200 - 诊断或实验用试剂及配制试剂；检定参照物','300210 - 抗血清、其他血份及免疫制品,不论是否修饰或通过生物工艺加工制得']

In [15]:
# all_l = dq_and_dz +jx_and_sb+ t_h_j +qx

In [16]:
# data = data.fillna(0)

In [17]:
# new_data = data[data["商品"] == all_l[0]]
# for i in all_l[1:]:
#     new_data = pd.concat([new_data,data[data["商品"] == i]],axis=0)

In [18]:
date_ck = date_ck.fillna(0)

In [19]:
shop_list = np.unique(date_ck["商品"])
coutry_list = np.unique(date_ck["贸易国"])
year_list = np.unique(date_ck["年"])

In [20]:
result_1y = np.zeros([len(coutry_list),len(coutry_list)])

In [21]:
all_d = []
for kkk in year_list:
    ddd = date_ck[date_ck["年"] == kkk]
    result_1y = np.zeros([len(coutry_list),len(coutry_list)])
    for i in range(len(coutry_list)):     
        for j in range(len(coutry_list)):
            d_i = ddd[ddd["贸易国"]==coutry_list[i]].iloc[:,2:]
            d_j = ddd[ddd["贸易国"]==coutry_list[j]].iloc[:,2:]
            result_ij = pd.merge(d_j, d_i, on='商品')
            result_1y[i,j] = result_ij.iloc[:,1:].min(axis=1).sum()
    all_d.append(result_1y)
    # df = pd.DataFrame(result_1y,columns=coutry_list,index=coutry_list)
    # with pd.ExcelWriter(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\esi.xlsx", engine='openpyxl', mode='a') as writer:
    #    df.to_excel(writer, sheet_name=kkk)

In [32]:
ddd[ddd["贸易国"]==coutry_list[1]].iloc[:,2:]

商品  出口金额（美元）
1849  300290 - 人血；医用动物血制品；毒素、培养微生物等  0.000020
1850                  380110 - 人造石墨  0.005449
1851                720299 - 未列名铁合金  0.005795
1852    847130 - 重量≤10kg的便携自动数据处理设备  0.724291
1853      847780 - 其他橡胶或塑料及其产品的加工机器  0.022451
1854                850231 - 风力发电机组  0.000016
1855                850760 - 锂离子蓄电池  0.241769
1856               852349 - 已录制光学媒体  0.000208

16

In [23]:
coutry_list[1:]

array(['印度', '印度尼西亚', '文莱', '新加坡', '新西兰', '日本', '柬埔寨', '泰国', '澳大利亚', '缅甸',
       '老挝', '菲律宾', '越南', '韩国', '马来西亚'], dtype=object)

In [24]:
dd = np.zeros([11,15])
for i in range(len(all_d)):
    dd[i]=(all_d[i][1:,1:].sum(axis=1)-1)*100/15

In [25]:
ccc = pd.DataFrame(dd.round(2),index=year_list,columns=coutry_list[1:])

In [27]:
ccc.to_excel(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\nnn.xlsx",index=True)

In [28]:
# C_ij=Σ[(RCAxik * RCAmjk)]*[W_k/W]。

In [29]:
data = data.fillna(0)

In [30]:
data["贸易额"] = data["进口金额（美元）"] + data["出口金额（美元）"]

In [31]:
data_sum = data.groupby("商品")["贸易额"].sum()

In [32]:
w_kw = data_sum/data_sum.sum()

In [33]:
data_sum_jc = data.groupby("商品")[["进口金额（美元）","出口金额（美元）"]].sum()

In [34]:
data_sum_jc

进口金额（美元）      出口金额（美元）
商品                                                                  
300210 - 抗血清、其他血份及免疫制品,不论是否修饰或通过生物工艺加工制得  7.399182e+08  2.206597e+08
300290 - 人血;医用动物血制品;毒素、培养微生物等             4.544900e+07  2.820463e+07
300290 - 人血；医用动物血制品；毒素、培养微生物等             2.197351e+09  4.266044e+08
380110 - 人造石墨                             1.976076e+09  5.075370e+09
382200 - 诊断或实验用试剂及配制试剂;检定参照物              1.066327e+09  2.811749e+08
382200 - 诊断或实验用试剂及配制试剂；检定参照物              9.037624e+09  5.520130e+09
390760 - 初级形状的聚对苯二甲酸乙二酯                   1.339052e+09  4.002692e+09
720299 - 未列名铁合金                           8.295944e+08  5.926029e+09
845610 - 用激光、其他光或光子束处理材料的加工机床             1.430500e+09  5.250070e+08
847130 - 重量≤10kg的便携自动数据处理设备               4.261693e+09  7.708024e+11
847780 - 其他橡胶或塑料及其产品的加工机器                 6.977352e+09  1.333046e+10
850231 - 风力发电机组                           1.284374e+08  7.569462e+09
850760 - 锂离子蓄电池                           4.418962e+10  1.663638e+11
851712 - 用于蜂窝网络或其他无线网络的电话机                5.812926e+09  7.817406e+11
852349 - 已录制光学媒体                          1.526437e+10  3.455212e+09
854140 - 光敏半导体器件;发光二极管                    2.808795e+10  4.446511e+10
854140 - 光敏半导体器件；发光二极管                    5.070887e+10  1.354630e+11

In [35]:
for i in  range(len(shop_list)):
    data.iloc[data[data["商品"] == shop_list[i]].index,4] = data[data["商品"] == shop_list[i]]["进口金额（美元）"]/data_sum_jc.iloc[i,0]
    data.iloc[data[data["商品"] == shop_list[i]].index,5] = data[data["商品"] == shop_list[i]]["出口金额（美元）"]/data_sum_jc.iloc[i,1]

In [36]:
data = data.fillna(0)

In [37]:
data["贸易互补系数"] = data["出口金额（美元）"]/(data["出口金额（美元）"]+data["进口金额（美元）"])

In [38]:
shop_list

array(['300210 - 抗血清、其他血份及免疫制品,不论是否修饰或通过生物工艺加工制得',
       '300290 - 人血;医用动物血制品;毒素、培养微生物等', '300290 - 人血；医用动物血制品；毒素、培养微生物等',
       '380110 - 人造石墨', '382200 - 诊断或实验用试剂及配制试剂;检定参照物',
       '382200 - 诊断或实验用试剂及配制试剂；检定参照物', '390760 - 初级形状的聚对苯二甲酸乙二酯',
       '720299 - 未列名铁合金', '845610 - 用激光、其他光或光子束处理材料的加工机床',
       '847130 - 重量≤10kg的便携自动数据处理设备', '847780 - 其他橡胶或塑料及其产品的加工机器',
       '850231 - 风力发电机组', '850760 - 锂离子蓄电池', '851712 - 用于蜂窝网络或其他无线网络的电话机',
       '852349 - 已录制光学媒体', '854140 - 光敏半导体器件;发光二极管',
       '854140 - 光敏半导体器件；发光二极管'], dtype=object)

表2-1：HS分类标准下的机电产品统计范围
商品名称Hs代码名称
1类金属产品HS83金属，贱金属     '720299 - 未列名铁合金'
第2类机械和设备HS84核反应堆、锅炉、机械和机械设备及其部件 '845610 - 用激光、其他光或光子束处理材料的加工机床' '847780 - 其他橡胶或塑料及其产品的加工机器','850231 - 风力发电机组'
第3类电气和电子产品HS85电动机、设备及其部件、磁带录音机和复制品  '847130 - 重量≤10kg的便携自动数据处理设备','850760 - 锂离子蓄电池','851712 - 用于蜂窝网络或其他无线网络的电话机','852349 - 已录制光学媒体','854140 - 光敏半导体器件;发光二极管','854140 - 光敏半导体器件；发光二极管'
第四类运输是指HS86铁路、有轨电车机车、铁路车辆机械部件、铁路或铁路设备、各种信号设备。
　	　HS87除铁路或有轨电车及其部件外的车辆
　	　HS88飞机、航天飞机及其部件
　	　HS89船舶、船只和浮动结构
      
5类器械HS90外科器械及器械、零配件


In [39]:
data.to_excel(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx",index=False)

In [40]:
dq_and_dz = ['847130 - 重量≤10kg的便携自动数据处理设备','850760 - 锂离子蓄电池','851712 - 用于蜂窝网络或其他无线网络的电话机','852349 - 已录制光学媒体','854140 - 光敏半导体器件;发光二极管','854140 - 光敏半导体器件；发光二极管']
jx_and_sb = ['845610 - 用激光、其他光或光子束处理材料的加工机床','847780 - 其他橡胶或塑料及其产品的加工机器','850231 - 风力发电机组']
t_h_j = ['720299 - 未列名铁合金']
qx = ['382200 - 诊断或实验用试剂及配制试剂；检定参照物','300210 - 抗血清、其他血份及免疫制品,不论是否修饰或通过生物工艺加工制得']

In [41]:
dd =data[data["商品"]== dq_and_dz[0]]
for i in range(1,len(dq_and_dz)):
     dd = pd.concat([data[data["商品"]== dq_and_dz[i]],dd])

In [42]:
del dd["出口金额（美元）"]
del dd["进口金额（美元）"]

In [44]:
with pd.ExcelWriter(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx", engine='openpyxl', mode='a') as writer:
       dd.to_excel(writer, sheet_name="电气和电子产品")

In [62]:
js = data[data["商品"]== jx_and_sb [0]]
for i in range(1,len(jx_and_sb)):
     js = pd.concat([data[data["商品"]== jx_and_sb[i]],js])

In [63]:
del js["出口金额（美元）"]
del js["进口金额（美元）"]

In [64]:
with pd.ExcelWriter(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx", engine='openpyxl', mode='a') as writer:
       js.to_excel(writer, sheet_name="机械和设备")

In [48]:
thj = data[data["商品"]== t_h_j [0]]

In [49]:
del thj["出口金额（美元）"]
del thj["进口金额（美元）"]

In [50]:
with pd.ExcelWriter(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx", engine='openpyxl', mode='a') as writer:
       thj.to_excel(writer, sheet_name="金属产品")

In [51]:
q_x =data[data["商品"]== qx[0]]
for i in range(1,len(qx)):
     q_x = pd.concat([data[data["商品"]== qx[i]],q_x])

In [52]:
del q_x["出口金额（美元）"]
del q_x["进口金额（美元）"]

In [53]:
with pd.ExcelWriter(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx", engine='openpyxl', mode='a') as writer:
       thj.to_excel(writer, sheet_name="器械")

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [66]:
d1 = pd.read_excel(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx",sheet_name="电气和电子产品")

In [67]:
d2 = pd.read_excel(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx",sheet_name="机械和设备")

In [68]:
d3 = pd.read_excel(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx",sheet_name="金属产品")

In [69]:
d4 = pd.read_excel(r"C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\贸易互补系数.xlsx",sheet_name="器械")

In [70]:
df = pd.concat([d1,d2,d3,d4])

In [71]:
d1.groupby("年")["贸易互补系数"].mean()

Unnamed: 0   统计国     年    贸易国                           商品          贸易额  \
0          1127  中国大陆  2018     世界       854140 - 光敏半导体器件；发光二极管  27414660575   
1          1135  中国大陆  2018     缅甸       854140 - 光敏半导体器件；发光二极管     13425830   
2          1143  中国大陆  2018    柬埔寨       854140 - 光敏半导体器件；发光二极管      5552261   
3          1154  中国大陆  2018   澳大利亚       854140 - 光敏半导体器件；发光二极管   1289518311   
4          1165  中国大陆  2018  印度尼西亚       854140 - 光敏半导体器件；发光二极管     98833944   
..          ...   ...   ...    ...                          ...          ...   
809        1852  中国大陆  2022     印度  847130 - 重量≤10kg的便携自动数据处理设备   5384840055   
810        1860  中国大陆  2022    新加坡  847130 - 重量≤10kg的便携自动数据处理设备   1915782114   
811        1867  中国大陆  2022     越南  847130 - 重量≤10kg的便携自动数据处理设备    938259110   
812        1874  中国大陆  2022     泰国  847130 - 重量≤10kg的便携自动数据处理设备    945785960   
813        1879  中国大陆  2022     文莱  847130 - 重量≤10kg的便携自动数据处理设备       229579   

       贸易互补系数  
0    0.425823  
1    1.000000  
2    1.000000  
3    0.999454  
4    0.230870  
..        ...  
809  0.999064  
810  0.995607  
811  0.009494  
812  0.999847  
813  1.000000  

[814 rows x 7 columns]

In [108]:
index = ["日本","澳大利亚","新西兰","韩国"]

In [130]:
index - list(d3.groupby(["年","贸易国"])["贸易互补系数"].mean()[2012].index)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [132]:
list(set(d3.groupby(["年","贸易国"])["贸易互补系数"].mean()[2012].index).intersection(set(index)))

['韩国', '日本', '新西兰', '澳大利亚']

In [86]:
yrs = [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [135]:
df.columns

Index(['hs85', 'hs84', 'hs83', 'hs90'], dtype='object')

In [141]:
import pandas as pd
from docx import Document
# 创建一个新的Word文档
doc = Document()
for yr in yrs:
    dd1 = d1.groupby(["年","贸易国"])["贸易互补系数"].mean()[yr]
    dd2 = d2.groupby(["年","贸易国"])["贸易互补系数"].mean()[yr]
    dd3 = d3.groupby(["年","贸易国"])["贸易互补系数"].mean()[yr]
    dd4 = d4.groupby(["年","贸易国"])["贸易互补系数"].mean()[yr]
    index_new = list(set(d3.groupby(["年","贸易国"])["贸易互补系数"].mean()[yr].index).intersection(set(index)))
    df = pd.concat([dd1[index_new],dd2[index_new],dd3[index_new],dd4[index_new]],axis=1)
        
    df.columns = ["hs85","hs84","hs83","hs90"]
    df.loc["东盟"] = [dd1.mean(),dd2.mean(),dd3.mean(),dd4.mean()]
    df = df.round(4)
    # 插入标题
    doc.add_heading('yr'+str(yr), level=1)

    # 将DataFrame转换为表格
    table = doc.add_table(df.shape[0]+1, df.shape[1]+1)
    c = ["country",'hs85', 'hs84', 'hs83', 'hs90']
    # 添加表头
    for i, column_name in enumerate(c):
        table.cell(0, i).text = column_name

    # 添加数据
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            table.cell(i+1, 0).text = str(df.index[i])
            table.cell(i+1, j+1).text = str(df.values[i, j])
    # # 保存文档
doc.save(r'C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\output_v4.docx')

In [115]:
d1.groupby(["年","贸易国"])["贸易互补系数"].mean()[yr][index]

贸易国
日本      0.746663
澳大利亚    0.695115
新西兰     0.718326
韩国      0.620622
Name: 贸易互补系数, dtype: float64

In [117]:
d1.groupby(["年","贸易国"])["贸易互补系数"].mean()[yr].mean()

0.7767641555417044

In [95]:
# df = pd.concat([d1.groupby("年")["贸易互补系数"].mean(),d2.groupby("年")["贸易互补系数"].mean(),d3.groupby("年")["贸易互补系数"].mean(),d4.groupby("年")["贸易互补系数"].mean()],axis=1)

In [28]:
df.columns = ["hs85","hs84","hs83","hs90"]

In [83]:
df.round(4)

贸易互补系数  贸易互补系数  贸易互补系数  贸易互补系数
年                                   
2012  0.7622  0.8636  0.8158  0.8158
2013  0.7627  0.8806  0.8530  0.8530
2014  0.7392  0.8782  0.8884  0.8884
2015  0.7552  0.8619  0.6577  0.6577
2016  0.7481  0.8886  0.8059  0.8059
2017  0.7385  0.9175  0.8026  0.8026
2018  0.7205  0.8634  0.7334  0.7334
2019  0.7382  0.8683  0.7465  0.7465
2020  0.7240  0.8804  0.6691  0.6691
2021  0.7422  0.9145  0.7049  0.7049
2022  0.7720  0.8792  0.8525  0.8525

In [98]:
df.shape[1]

4

In [30]:
import pandas as pd
from docx import Document


# 创建一个新的Word文档
doc = Document()

# 插入标题
doc.add_heading('DataFrame', level=1)

# 将DataFrame转换为表格
table = doc.add_table(df.shape[0]+1, df.shape[1])

# 添加表头
for i, column_name in enumerate(df.columns):
    table.cell(0, i).text = column_name

# 添加数据
for i in range(df.shape[0]):
    for j in range(df.shape[1]):
        table.cell(i+1, j).text = str(df.values[i, j])

# # 保存文档
# doc.save(r'C:\Users\lll23\Desktop\应用\数据分析\实战\mid\date_js\output.docx')
